# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9917db3234832251e4821734db5ec26e7a79c219770565d6af56c8803fe655d3452349141ae980eb606f60c55281c3971acf6b169bd45bcd819f6fc2ee26c83a

test:
  secret_key_base: adb6f87c43d635d898208674f0af45ee9cd24d586d3a74d51e91691510621b3760669eb4999258810ae87f7105889553053f1fb92aa44a4287c2f3db1e2edc94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
